[package]
name = "zipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "5.1.4"
clap = { version = "4.5.4", features = ["derive"] }
splitfile = "0.2.0"
zip = "1.1.3"
